#!/bin/bash
# static today code

YESTARDAY=`date -v-1d +%F`
TODAY=`date -v-0d +%F`

git log --since=$YESTARDAY --until=$TODAY --author="$(git config --get user.name)" --pretty=tformat: --numstat \
| awk '{ add += $1 ; subs += $2 ; loc += $1 + $2 } END { printf "added lines: %s removed lines : %s total lines: %s\n",add,subs,loc }'
